// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { AppSidebar } from "@/layOut/app-sidebar";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/customComponent/app-sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // ${geistSans.variable} ${geistMono.variable}
        className={` antialiased`}
      >
        <SidebarProvider>
        <AppSidebar/>

        {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
